# Created by: Makefile generated by sarmasag@raress.tech
# Created on: 2024-12-12 17:52:21
# Languages: Ruby, Python, Perl, Lua, Scala and C


##### Entry point - main languages: lUA, Ruby #####


#$$$$ Uncomment me for Lua

# .PHONY: build run

# # sources
# SRC = sat.lua

# # pass build
# build:
	
# # run for set input & output
# run:
# 	@lua $(SRC) $(INPUT) $(OUTPUT)


#$$$$ Uncomment me for Ruby

.PHONY: build run

# sources
SRC = sat.rb

# pass build
build:
	
# run for set input & output
run:
	@ruby $(SRC) $(INPUT) $(OUTPUT)


##### Legacy code - languages: Python, Perl, Scala and C #####


#$$$$ Uncomment me for C
# .PHONY: build run

# # sources & target
# SRC = sat.c
# OUT = sat

# # build target
# build:
# 	@gcc -O3 -march=native -o $(OUT) $(SRC)

# # run for set input & output
# run:
# 	@./$(OUT) $(INPUT) $(OUTPUT)


#$$$$ Uncomment me for Perl
# .PHONY: build run

# # sources
# SRC = sat.pl

# # pass build
# build:
	
# # run for set input & output
# run:
# 	@perl sat.pl $(INPUT) $(OUTPUT)


#$$$$ Uncomment me for Scala
# .PHONY: build run

# # sources & target
# SRC = sat.scala

# # pass build
# build:

# # run for set input & output
# run:
# 	@scala $(SRC) $(INPUT) $(OUTPUT)